2021-03-09 20:14:26,838 INFO    MainThread:31298 [wandb_setup.py:_flush():70] setting env: {}
2021-03-09 20:14:26,838 INFO    MainThread:31298 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-03-09 20:14:26,839 INFO    MainThread:31298 [wandb_setup.py:_flush():70] setting login settings: {}
2021-03-09 20:14:26,839 INFO    MainThread:31298 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f99fdebf460>
2021-03-09 20:14:26,839 INFO    MainThread:31298 [wandb_init.py:_log_setup():319] Logging user logs to /home/johannbs/Desktop/IceCube_GNN2/wandb/run-20210309_201426-ii5q2lb7/logs/debug.log
2021-03-09 20:14:26,840 INFO    MainThread:31298 [wandb_init.py:_log_setup():320] Logging internal logs to /home/johannbs/Desktop/IceCube_GNN2/wandb/run-20210309_201426-ii5q2lb7/logs/debug-internal.log
2021-03-09 20:14:26,840 INFO    MainThread:31298 [wandb_init.py:init():351] calling init triggers
2021-03-09 20:14:26,840 INFO    MainThread:31298 [wandb_init.py:init():356] wandb.init called with sweep_config: {}
config: {}
2021-03-09 20:14:26,840 INFO    MainThread:31298 [wandb_init.py:init():404] starting backend
2021-03-09 20:14:26,854 INFO    MainThread:31298 [backend.py:ensure_launched():81] starting backend process...
2021-03-09 20:14:26,863 INFO    MainThread:31298 [backend.py:ensure_launched():85] started backend process with pid: 31330
2021-03-09 20:14:26,864 INFO    MainThread:31298 [wandb_init.py:init():413] backend started and connected
2021-03-09 20:14:26,866 INFO    MainThread:31298 [wandb_init.py:init():436] updated telemetry
2021-03-09 20:14:26,867 INFO    MainThread:31298 [wandb_init.py:init():459] communicating current version
2021-03-09 20:14:27,744 INFO    MainThread:31298 [wandb_init.py:init():464] got version response upgrade_message: "wandb version 0.10.21 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-09 20:14:27,745 INFO    MainThread:31298 [wandb_init.py:init():472] communicating run to backend with 30 second timeout
2021-03-09 20:14:27,948 INFO    MainThread:31298 [wandb_init.py:init():495] starting run threads in backend
2021-03-09 20:14:29,450 INFO    MainThread:31298 [wandb_run.py:_console_start():1411] atexit reg
2021-03-09 20:14:29,451 INFO    MainThread:31298 [wandb_run.py:_redirect():1274] redirect: SettingsConsole.WRAP
2021-03-09 20:14:29,451 INFO    MainThread:31298 [wandb_run.py:_redirect():1309] Wrapping output streams.
2021-03-09 20:14:29,451 INFO    MainThread:31298 [wandb_run.py:_redirect():1325] Redirects installed.
2021-03-09 20:14:29,451 INFO    MainThread:31298 [wandb_init.py:init():518] run started, returning control to user process
2021-03-09 20:14:29,458 INFO    MainThread:31298 [wandb_init.py:_pause_backend():240] pausing backend
2021-03-09 20:14:58,178 INFO    MainThread:31298 [wandb_init.py:_resume_backend():245] resuming backend
2021-03-09 20:14:58,179 INFO    MainThread:31298 [wandb_init.py:_pause_backend():240] pausing backend
2021-03-09 20:14:58,179 INFO    MainThread:31298 [wandb_run.py:_atexit_cleanup():1381] got exitcode: 0
2021-03-09 20:14:58,180 INFO    MainThread:31298 [wandb_run.py:_restore():1353] restore
2021-03-09 20:14:58,416 INFO    MainThread:31298 [wandb_run.py:_wait_for_finish():1504] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 801
  total_bytes: 801
}

2021-03-09 20:15:00,421 INFO    MainThread:31298 [wandb_run.py:_wait_for_finish():1504] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8110
  total_bytes: 8110
}

2021-03-09 20:15:01,719 INFO    MainThread:31298 [wandb_run.py:_show_files():1726] logging synced files
